import type { RecipeSeed } from './recipes'

export const recipeSlice6Seeds: RecipeSeed[] = [
  { id: 'thai-papaya-salad', sourceId: 'slice6-01', name: 'ส้มตำไทยดั้งเดิม', englishName: 'Thai Papaya Salad (Som Tam)', category: 'Light bowls', cuisine: 'Thai', servings: 2, prepMinutes: 20, cookMinutes: 0, ingredients: [{ item: 'Green papaya, shredded', amount: '300 g' }, { item: 'Long beans, cut into short lengths', amount: '80 g' }, { item: 'Cherry tomatoes, halved', amount: '100 g' }, { item: 'Garlic, minced', amount: '2 cloves' }, { item: "Bird's eye chilli, sliced", amount: '2' }, { item: 'Lime juice', amount: '2 tbsp' }, { item: 'Fish sauce', amount: '1½ tbsp' }, { item: 'Brown sugar', amount: '1 tbsp' }, { item: 'Roasted peanuts, chopped', amount: '2 tbsp' }], instructions: ['Pound garlic and chilli together in a mortar (or crush with the back of a knife) until fragrant, then add the long beans and bruise briefly.', 'Add the shredded papaya and tomatoes; lightly bruise everything together with a spoon and pestle so the flavors combine without turning the salad mushy.', 'Season with fish sauce, lime juice and brown sugar; toss well and taste, adjusting lime and sugar to balance sour, salty and sweet.', 'Scatter with roasted peanuts and serve immediately while the papaya is crisp. Fold through a spoonful of dried shrimp for a more traditional finish, if desired.'], nutrition: { kcal: 170, protein: 5, carbs: 26, fat: 5, fiber: 4, sodium: 640 }, tags: ['Light', 'No-cook', 'Gluten-free'], accent: 'lime' },
  { id: 'japanese-beef-gyudon', sourceId: 'slice6-02', name: 'ข้าวหน้าเนื้อเกียวด้ง', englishName: 'Japanese Beef Gyudon', category: 'Quick meals', cuisine: 'Japanese', servings: 2, prepMinutes: 10, cookMinutes: 15, ingredients: [{ item: 'Lean beef strips', amount: '280 g' }, { item: 'Onion, thinly sliced', amount: '1 medium' }, { item: 'Dashi stock', amount: '300 ml' }, { item: 'Reduced-sodium soy sauce', amount: '2 tbsp' }, { item: 'Brown sugar', amount: '1 tbsp' }, { item: 'Ginger, grated', amount: '1 tsp' }, { item: 'Brown rice, cooked', amount: '1 cup' }, { item: 'Spring onion, sliced', amount: '2 stalks' }], instructions: ['Bring the dashi stock to a simmer with the soy sauce, brown sugar and ginger.', 'Add the onion and simmer for 4–5 minutes until it softens and turns translucent.', 'Add the beef in a single layer and simmer gently, without stirring too much, until just cooked through and the broth has reduced slightly, about 4 minutes.', 'Spoon the beef, onion and a little broth over bowls of brown rice, and finish with spring onion.'], nutrition: { kcal: 465, protein: 32, carbs: 50, fat: 15, fiber: 3, sodium: 620 }, tags: ['High protein', 'Quick', 'Balanced'], accent: 'gold' },
  { id: 'japanese-vegetable-curry-rice', sourceId: 'slice6-03', name: 'ข้าวแกงกะหรี่ญี่ปุ่นผัก', englishName: 'Japanese Vegetable Curry Rice', category: 'Plant-forward', cuisine: 'Japanese', servings: 2, prepMinutes: 15, cookMinutes: 17, ingredients: [{ item: 'Onion, sliced', amount: '1 medium' }, { item: 'Carrot, sliced', amount: '1 medium' }, { item: 'Sweet potato, cubed', amount: '250 g' }, { item: 'Chickpeas, rinsed', amount: '1 cup' }, { item: 'Curry powder', amount: '2 tbsp' }, { item: 'Reduced-sodium soy sauce', amount: '1 tsp' }, { item: 'Brown sugar', amount: '1 tsp' }, { item: 'Neutral oil', amount: '1 tsp' }, { item: 'Low-sodium vegetable stock', amount: '500 ml' }, { item: 'Brown rice, cooked', amount: '1½ cups' }], instructions: ['Heat the oil in a pot and cook the onion until soft and lightly golden, about 5 minutes.', 'Stir in the curry powder and cook for 30 seconds until fragrant.', 'Add the stock, carrot, sweet potato and chickpeas; bring to a simmer and cook for 15 minutes until the vegetables are tender.', 'Stir in the soy sauce and brown sugar, then mash a few pieces of sweet potato against the side of the pot to thicken the sauce. Simmer for 2 more minutes and serve over brown rice.'], nutrition: { kcal: 400, protein: 12, carbs: 62, fat: 12, fiber: 10, sodium: 480 }, tags: ['Vegetarian', 'Balanced', 'Comforting'], accent: 'coral' },
  { id: 'garlic-pepper-pork-fried-egg-rice', sourceId: 'slice6-04', name: 'ข้าวหมูกระเทียมพริกไทยไข่ดาว', englishName: 'Garlic Pepper Pork with Fried Egg', category: 'Quick meals', cuisine: 'Thai', servings: 2, prepMinutes: 15, cookMinutes: 12, ingredients: [{ item: 'Lean pork loin, thinly sliced', amount: '300 g' }, { item: 'Coriander root and garlic, pounded', amount: '2 tsp' }, { item: 'Ground black pepper', amount: '1½ tsp' }, { item: 'Fish sauce', amount: '1 tbsp' }, { item: 'Eggs', amount: '2' }, { item: 'Cooked jasmine rice', amount: '1½ cups' }, { item: 'Cucumber, sliced', amount: '1 small' }, { item: 'Neutral oil', amount: '1 tsp' }, { item: 'Coriander leaves, chopped', amount: '2 tbsp' }], instructions: ['Pound or mince garlic and coriander root together, then mix with the pork, black pepper and half the fish sauce; marinate for 10 minutes.', 'Heat half the oil in a non-stick pan and fry the eggs until the whites are set and the edges are crisp; set aside.', 'Using the remaining oil, sear the pork in a hot pan until the garlic is golden and the pork is cooked through, about 4–5 minutes, adding the remaining fish sauce partway through.', 'Serve the pork over jasmine rice with a fried egg, cucumber and coriander.'], nutrition: { kcal: 520, protein: 34, carbs: 52, fat: 19, fiber: 2, sodium: 610 }, tags: ['High protein', 'Quick', 'Balanced'], accent: 'gold' },
]

export const recipeImagePresentationSlice6: Record<string, string> = {
  'thai-papaya-salad': 'A shallow ceramic bowl of shredded green papaya salad with halved cherry tomatoes and long beans, topped with chopped roasted peanuts, limes and dried chillies beside the bowl. No tofu, no salted egg, no crab, no noodles.',
  'japanese-beef-gyudon': 'A donburi bowl of thin-sliced simmered beef and soft onion over rice, garnished with pickled red ginger and spring onion, a small bowl of miso soup alongside. No egg poured or set into the beef.',
  'japanese-vegetable-curry-rice': 'A plate of thick brown Japanese-style curry with carrot, sweet potato and broccoli pieces, served beside a mound of white rice. No visible meat, no coconut-milk sheen.',
  'garlic-pepper-pork-fried-egg-rice': 'A plate of seared garlic-pepper pork over rice with a crisp-edged fried egg, sliced cucumber and a small side of chilli sauce, scattered with fried garlic and spring onion.',
}
