import { cuisineText } from './i18n'
import { isIngredientUnit, isValidIngredientQuantity, parseIngredientMeasurement } from './measurements'
import { canonicalIngredientIdForItem, canonicalIngredientIds } from './pantry'
import { thaiRecipeContent } from './recipe-content'
import { recipeExpansionSeeds } from './recipe-expansion'
import type { Filters, LocalizedText, Recipe } from './types'

export const emptyFilters: Filters = { category: '', tags: [] }

export type RecipeSeed = Omit<Recipe, 'image' | 'name' | 'cuisine' | 'ingredients' | 'instructions'> & {
  name: string
  englishName: string
  cuisine: string
  ingredients: { item: string; amount: string }[]
  instructions: string[]
  image?: string
}

const r = (recipe: RecipeSeed): Recipe => {
  const content = thaiRecipeContent[recipe.id]
  if (!content || content.ingredients.length !== recipe.ingredients.length || content.instructions.length !== recipe.instructions.length) throw new Error(`Incomplete Thai recipe content: ${recipe.id}`)
  const { name, englishName, cuisine, ingredients, instructions, image, ...shared } = recipe
  return {
    ...shared,
    name: { th: content.name, en: englishName },
    cuisine: cuisineText(cuisine),
    ingredients: ingredients.map((ingredient, index) => ({ item: { th: content.ingredients[index], en: ingredient.item }, ...parseIngredientMeasurement(ingredient.amount, ingredient.item), ingredientId: canonicalIngredientIdForItem(ingredient.item), amount: ingredient.amount })),
    instructions: instructions.map((instruction, index) => ({ th: content.instructions[index], en: instruction })),
    image: image ?? `/recipes/${recipe.id}.webp`,
  }
}

export const recipes: Recipe[] = [
  r({ id:'tom-yum-prawns', sourceId:'f002', name:'ต้มยำกุ้งน้ำใส', englishName:'Clear Tom Yum Prawns', category:'Thai favorites', cuisine:'Thai', servings:2, prepMinutes:12, cookMinutes:10, ingredients:[{item:'Prawns, peeled',amount:'220 g'},{item:'Mushrooms, halved',amount:'150 g'},{item:'Tom yum herbs (lemongrass, galangal, lime leaves)',amount:'1 small bundle'},{item:'Cherry tomatoes',amount:'120 g'},{item:'Lime juice',amount:'2 tbsp'},{item:'Fish sauce',amount:'1½ tsp'}], instructions:['Bring 700 ml water to a gentle simmer with the tom yum herbs for 4 minutes.','Add mushrooms and tomatoes; cook until just softened.','Add prawns and poach until opaque, 2–3 minutes. Turn off the heat.','Season with lime juice and fish sauce, tasting before adding more salt.'], nutrition:{kcal:150,protein:16,carbs:9,fat:3,fiber:3,sodium:360}, tags:['High protein','Light','Gluten-free'], accent:'coral' }),
  r({ id:'glass-noodle-seafood-salad', sourceId:'f008', name:'ยำวุ้นเส้นทะเล', englishName:'Glass Noodle Seafood Salad', category:'Light bowls', cuisine:'Thai', servings:2, prepMinutes:15, cookMinutes:8, ingredients:[{item:'Glass noodles, dry',amount:'70 g'},{item:'Mixed seafood',amount:'220 g'},{item:'Tomato, wedges',amount:'1 medium'},{item:'Red onion, sliced',amount:'¼ cup'},{item:'Celery, sliced',amount:'½ cup'},{item:'Lime juice',amount:'2 tbsp'},{item:'Fish sauce',amount:'1 tsp'}], instructions:['Soak or cook noodles according to the packet, then cool briefly.','Poach seafood in simmering water until cooked through, then drain.','Toss noodles, seafood, tomato, onion and celery.','Dress with lime juice and fish sauce just before serving.'], nutrition:{kcal:220,protein:18,carbs:25,fat:6,fiber:3,sodium:690}, tags:['High protein','Light','Dairy-free'], accent:'lime' }),
  r({ id:'tofu-mince-soup', sourceId:'f038', name:'แกงจืดเต้าหู้หมูสับ', englishName:'Tofu & Pork Mince Soup', category:'Thai favorites', cuisine:'Thai', servings:2, prepMinutes:10, cookMinutes:15, ingredients:[{item:'Lean pork mince',amount:'180 g'},{item:'Firm tofu, cubed',amount:'200 g'},{item:'Chinese cabbage, chopped',amount:'180 g'},{item:'Coriander root and garlic, pounded',amount:'1 tsp'},{item:'Low-sodium stock',amount:'750 ml'},{item:'Light soy sauce',amount:'1 tsp'}], instructions:['Mix pork with the pounded coriander root and garlic; form small balls.','Bring stock to a simmer and add pork balls for 5 minutes.','Add cabbage and tofu; simmer gently until the cabbage is tender.','Season lightly with soy sauce and finish with coriander.'], nutrition:{kcal:240,protein:25,carbs:10,fat:11,fiber:3,sodium:610}, tags:['Comforting','High protein','Low carb'], accent:'violet' }),
  r({ id:'herb-grilled-chicken', sourceId:'f042', name:'ไก่ย่างสมุนไพรกับผัก', englishName:'Herb Grilled Chicken & Vegetables', category:'High protein', cuisine:'Thai', servings:2, prepMinutes:15, cookMinutes:18, ingredients:[{item:'Skinless chicken thighs',amount:'300 g'},{item:'Garlic, grated',amount:'2 cloves'},{item:'Coriander root, pounded',amount:'1 tsp'},{item:'Broccoli florets',amount:'180 g'},{item:'Carrot, sliced',amount:'1 medium'},{item:'Brown rice, cooked',amount:'1 cup'}], instructions:['Rub chicken with garlic and coriander root; rest for 10 minutes.','Grill or pan-sear chicken until the centre is fully cooked, about 6–8 minutes per side.','Steam broccoli and carrot until crisp-tender.','Slice chicken and serve with vegetables and brown rice.'], nutrition:{kcal:420,protein:40,carbs:34,fat:14,fiber:6,sodium:480}, tags:['High protein','Meal prep','Gluten-free'], accent:'gold' }),
  r({ id:'cold-soba-edamame', sourceId:'f076', name:'โซบะเย็นเอเดมาเมะ', englishName:'Cold Soba with Edamame', category:'Quick meals', cuisine:'Japanese', servings:2, prepMinutes:10, cookMinutes:8, ingredients:[{item:'Buckwheat soba',amount:'150 g'},{item:'Shelled edamame',amount:'120 g'},{item:'Cucumber, ribbons',amount:'1 small'},{item:'Carrot, julienned',amount:'1 small'},{item:'Reduced-sodium soy sauce',amount:'1 tbsp'},{item:'Rice vinegar',amount:'1 tbsp'}], instructions:['Cook soba until tender and rinse under cold water.','Steam edamame for 3 minutes and cool.','Whisk soy sauce with rice vinegar and 2 tbsp water.','Toss noodles, vegetables and edamame with dressing.'], nutrition:{kcal:350,protein:16,carbs:58,fat:6,fiber:7,sodium:520}, tags:['Plant protein','Quick','Dairy-free'], accent:'blue' }),
  r({ id:'salmon-teriyaki-bowl', sourceId:'f079', name:'แซลมอนย่างเทอริยากิ', englishName:'Lighter Teriyaki Salmon Bowl', category:'High protein', cuisine:'Japanese', servings:2, prepMinutes:12, cookMinutes:15, ingredients:[{item:'Salmon fillets',amount:'280 g'},{item:'Reduced-sodium teriyaki sauce',amount:'1½ tbsp'},{item:'Brown rice, cooked',amount:'1 cup'},{item:'Broccoli',amount:'200 g'},{item:'Sesame seeds',amount:'1 tsp'}], instructions:['Brush salmon with half the sauce.','Bake or pan-sear salmon until it flakes easily, 10–12 minutes.','Steam broccoli until bright green and tender.','Serve with rice, broccoli, remaining sauce and sesame.'], nutrition:{kcal:480,protein:32,carbs:40,fat:22,fiber:6,sodium:680}, tags:['High protein','Omega-rich','Meal prep'], accent:'coral' }),
  r({ id:'veggie-bibimbap', sourceId:'f117', name:'ข้าวยำเกาหลีผักและไข่', englishName:'Vegetable Bibimbap with Egg', category:'Plant-forward', cuisine:'Korean', servings:2, prepMinutes:20, cookMinutes:15, ingredients:[{item:'Brown rice, cooked',amount:'1½ cups'},{item:'Eggs',amount:'2'},{item:'Spinach',amount:'120 g'},{item:'Carrot, matchsticks',amount:'1 medium'},{item:'Mushrooms, sliced',amount:'150 g'},{item:'Gochujang',amount:'2 tsp'}], instructions:['Sauté mushrooms and carrots separately with a splash of water.','Wilt spinach in a hot pan and season lightly.','Fry eggs to your preferred doneness.','Build bowls with rice, vegetables, egg and a small spoonful of gochujang.'], nutrition:{kcal:420,protein:16,carbs:60,fat:12,fiber:8,sodium:570}, tags:['Vegetarian','Fiber-rich','Balanced'], accent:'red' }),
  r({ id:'mango-vietnamese-salad', sourceId:'f134', name:'สลัดเวียดนามยำมะม่วง', englishName:'Vietnamese Mango Herb Salad', category:'Light bowls', cuisine:'Vietnamese', servings:2, prepMinutes:18, cookMinutes:0, ingredients:[{item:'Green mango, julienned',amount:'1 medium'},{item:'Cucumber, ribbons',amount:'1 small'},{item:'Mint and coriander',amount:'1 cup'},{item:'Roasted peanuts, chopped',amount:'1 tbsp'},{item:'Lime juice',amount:'2 tbsp'},{item:'Fish sauce',amount:'1 tsp'}], instructions:['Combine mango, cucumber and herbs in a wide bowl.','Mix lime juice with fish sauce and 1 tbsp water.','Toss the salad with dressing immediately before serving.','Scatter with peanuts.'], nutrition:{kcal:150,protein:6,carbs:22,fat:4,fiber:5,sodium:390}, tags:['Light','No-cook','Dairy-free'], accent:'gold' }),
  r({ id:'steamed-lime-seabass', sourceId:'f194', name:'ปลากะพงนึ่งมะนาว', englishName:'Steamed Lime Sea Bass', category:'Thai favorites', cuisine:'Thai', servings:2, prepMinutes:15, cookMinutes:15, ingredients:[{item:'Sea bass fillets',amount:'300 g'},{item:'Garlic, minced',amount:'3 cloves'},{item:'Lime juice',amount:'3 tbsp'},{item:'Bird’s eye chilli, sliced',amount:'1–2'},{item:'Chinese celery',amount:'½ cup'},{item:'Jasmine rice, cooked',amount:'1 cup'}], instructions:['Place fish on a heatproof plate and steam until opaque, 12–15 minutes.','Mix garlic, lime juice, chilli and 2 tbsp warm water.','Spoon sauce over the cooked fish and top with celery.','Serve with rice and extra vegetables.'], nutrition:{kcal:285,protein:34,carbs:28,fat:4,fiber:2,sodium:620}, tags:['High protein','Gluten-free','Light'], accent:'aqua' }),
  r({ id:'prawn-rice-congee', sourceId:'f241', name:'ข้าวต้มกุ้งขิง', englishName:'Ginger Prawn Rice Congee', category:'Quick meals', cuisine:'Thai', servings:2, prepMinutes:8, cookMinutes:20, ingredients:[{item:'Cooked jasmine rice',amount:'1½ cups'},{item:'Prawns, peeled',amount:'180 g'},{item:'Ginger, julienned',amount:'1 tbsp'},{item:'Mushrooms, sliced',amount:'120 g'},{item:'Low-sodium stock',amount:'750 ml'},{item:'Spring onion',amount:'2 stalks'}], instructions:['Simmer rice and stock for 15 minutes, stirring until porridge-like.','Add ginger and mushrooms; cook 3 minutes.','Add prawns and cook until opaque.','Top with spring onion and season sparingly.'], nutrition:{kcal:260,protein:18,carbs:35,fat:5,fiber:3,sodium:560}, tags:['Comforting','High protein','Low fat'], accent:'violet' }),
  r({ id:'gazpacho-chickpea', sourceId:'f259', name:'กัซปาโชถั่วชิกพี', englishName:'Gazpacho with Chickpeas', category:'Plant-forward', cuisine:'Spanish', servings:2, prepMinutes:15, cookMinutes:0, ingredients:[{item:'Ripe tomatoes, chopped',amount:'500 g'},{item:'Cucumber, chopped',amount:'½ large'},{item:'Red bell pepper',amount:'1'},{item:'Chickpeas, rinsed',amount:'1 cup'},{item:'Olive oil',amount:'1 tsp'},{item:'Red wine vinegar',amount:'1 tbsp'}], instructions:['Blend tomatoes, cucumber, pepper, vinegar and olive oil until smooth.','Chill for 10 minutes if time allows.','Divide into bowls and top with chickpeas.','Season with black pepper and fresh herbs.'], nutrition:{kcal:240,protein:9,carbs:36,fat:7,fiber:10,sodium:320}, tags:['Vegan','No-cook','Fiber-rich'], accent:'red' }),
  r({ id:'salmon-poke-bowl', sourceId:'f270', name:'โพเกโบวล์แซลมอน', englishName:'Salmon Poke Bowl', category:'Light bowls', cuisine:'Hawaiian', servings:2, prepMinutes:18, cookMinutes:0, ingredients:[{item:'Sushi-grade salmon, cubed and kept chilled',amount:'220 g'},{item:'Brown rice, cooked',amount:'1 cup'},{item:'Edamame, cooked',amount:'100 g'},{item:'Cucumber, cubed',amount:'1 small'},{item:'Avocado, sliced',amount:'½'},{item:'Lime juice',amount:'1 tbsp'},{item:'Reduced-sodium soy sauce',amount:'2 tsp'}], instructions:['Place chilled sushi-grade salmon in a bowl with soy sauce and lime juice.','Divide rice, cooked edamame, cucumber and avocado between bowls.','Add salmon to each bowl.','Finish with sesame or nori if desired.'], nutrition:{kcal:480,protein:28,carbs:50,fat:18,fiber:8,sodium:510}, tags:['High protein','Omega-rich','No-cook'], accent:'aqua' }),
  r({ id:'grilled-mackerel-bowl', sourceId:'f297', name:'ปลาซาบะย่างกับข้าวกล้อง', englishName:'Grilled Mackerel Brown Rice Bowl', category:'High protein', cuisine:'Japanese', servings:2, prepMinutes:10, cookMinutes:15, ingredients:[{item:'Mackerel fillets',amount:'260 g'},{item:'Brown rice, cooked',amount:'1 cup'},{item:'Green beans',amount:'180 g'},{item:'Lemon',amount:'½'},{item:'Reduced-sodium soy sauce',amount:'1 tsp'}], instructions:['Grill mackerel skin-side down until crisp and cooked through.','Steam green beans until tender-crisp.','Divide rice and beans between bowls.','Add mackerel, lemon and a small drizzle of soy sauce.'], nutrition:{kcal:420,protein:30,carbs:40,fat:16,fiber:7,sodium:500}, tags:['High protein','Omega-rich','Meal prep'], accent:'blue' }),
  r({ id:'broccoli-prawn-stirfry', sourceId:'f433', name:'ผัดบรอกโคลีกุ้ง', englishName:'Broccoli Prawn Stir-fry', category:'Quick meals', cuisine:'Chinese', servings:2, prepMinutes:12, cookMinutes:10, ingredients:[{item:'Prawns, peeled',amount:'240 g'},{item:'Broccoli florets',amount:'280 g'},{item:'Garlic, sliced',amount:'3 cloves'},{item:'Oyster sauce',amount:'2 tsp'},{item:'Neutral oil',amount:'1 tsp'},{item:'Brown rice, cooked',amount:'1 cup'}], instructions:['Heat oil and cook garlic briefly until fragrant.','Add prawns and stir-fry until nearly cooked.','Add broccoli with 3 tbsp water, cover for 2 minutes.','Stir in oyster sauce and serve with rice.'], nutrition:{kcal:270,protein:20,carbs:30,fat:8,fiber:6,sodium:580}, tags:['High protein','Quick','Dairy-free'], accent:'lime' }),
  r({ id:'fruit-yogurt-bowl', sourceId:'f313', name:'โยเกิร์ตผลไม้และเมล็ดพืช', englishName:'Fruit Yogurt Seed Bowl', category:'Light bowls', cuisine:'American', servings:1, prepMinutes:8, cookMinutes:0, ingredients:[{item:'Plain Greek yogurt',amount:'170 g'},{item:'Mixed fruit',amount:'1 cup'},{item:'Chia seeds',amount:'1 tsp'},{item:'Oats',amount:'2 tbsp'},{item:'Cinnamon',amount:'a pinch'}], instructions:['Spoon yogurt into a bowl.','Top with fruit, oats and chia seeds.','Finish with cinnamon.','Serve straight away.'], nutrition:{kcal:290,protein:20,carbs:38,fat:7,fiber:7,sodium:95}, tags:['High protein','No-cook','Vegetarian'], accent:'coral' }),
  r({ id:'grilled-chicken-jaew', sourceId:'slice1-01', name:'ไก่ย่างแจ่วกับข้าวกล้อง', englishName:'Grilled Chicken with Jaew Sauce', category:'Quick meals', cuisine:'Thai', servings:2, prepMinutes:15, cookMinutes:16, ingredients:[{item:'Skinless chicken breast',amount:'300 g'},{item:'Brown rice, cooked',amount:'1 cup'},{item:'Cucumber, sliced',amount:'150 g'},{item:'Shallot, thinly sliced',amount:'2 tbsp'},{item:'Lime juice',amount:'2 tbsp'},{item:'Toasted rice powder',amount:'1 tbsp'},{item:'Fish sauce',amount:'1 tsp'},{item:'Dried chilli flakes',amount:'½ tsp'}], instructions:['Season chicken with half the lime juice and a pinch of chilli; rest for 10 minutes.','Grill or pan-sear until cooked through, about 7–8 minutes per side, then slice.','Mix remaining lime juice, fish sauce, toasted rice and shallot into a jaew sauce.','Serve chicken with brown rice, cucumber and sauce.'], nutrition:{kcal:410,protein:38,carbs:42,fat:10,fiber:5,sodium:520}, tags:['High protein','Balanced','Meal prep'], accent:'coral' }),
  r({ id:'chicken-basil-rice-egg', sourceId:'slice1-02', name:'ข้าวกะเพราไก่ไข่ดาว', englishName:'Chicken Basil Rice with Fried Egg', category:'Thai favorites', cuisine:'Thai', servings:2, prepMinutes:10, cookMinutes:15, ingredients:[{item:'Lean chicken mince',amount:'260 g'},{item:'Cooked jasmine rice',amount:'1 cup'},{item:'Eggs',amount:'2'},{item:'Thai holy basil',amount:'1 packed cup'},{item:'Long beans, sliced',amount:'100 g'},{item:'Bird’s eye chilli, sliced',amount:'2'},{item:'Fish sauce',amount:'1 tsp'}], instructions:['Warm a non-stick pan and stir-fry chicken with chilli until no longer pink.','Add long beans and 2 tablespoons of water; cook until crisp-tender.','Season with fish sauce, fold in basil and turn off the heat.','Top each rice portion with the chicken and one fried egg.'], nutrition:{kcal:520,protein:33,carbs:55,fat:19,fiber:4,sodium:650}, tags:['High protein','Balanced','Quick'], accent:'lime' }),
  r({ id:'chicken-larb-brown-rice', sourceId:'slice1-03', name:'ลาบไก่กับข้าวกล้อง', englishName:'Chicken Larb with Brown Rice', category:'Light bowls', cuisine:'Thai', servings:2, prepMinutes:15, cookMinutes:10, ingredients:[{item:'Lean chicken mince',amount:'260 g'},{item:'Brown rice, cooked',amount:'1 cup'},{item:'Cabbage, shredded',amount:'180 g'},{item:'Mint leaves',amount:'½ cup'},{item:'Shallot, sliced',amount:'¼ cup'},{item:'Lime juice',amount:'2 tbsp'},{item:'Toasted rice powder',amount:'1 tbsp'},{item:'Fish sauce',amount:'1 tsp'}], instructions:['Cook chicken mince in a dry pan with 2 tablespoons of water until fully cooked.','Remove from heat and mix with lime juice, fish sauce and toasted rice powder.','Fold in shallot and mint.','Serve with brown rice and shredded cabbage.'], nutrition:{kcal:390,protein:34,carbs:43,fat:10,fiber:6,sodium:540}, tags:['High protein','Light','Meal prep'], accent:'aqua' }),
  r({ id:'spicy-tuna-salad', sourceId:'slice1-04', name:'ยำทูน่าเผ็ดสด', englishName:'Spicy Tuna Salad', category:'Light bowls', cuisine:'Thai', servings:2, prepMinutes:12, cookMinutes:0, ingredients:[{item:'Tuna in spring water, drained',amount:'240 g'},{item:'Romaine lettuce, torn',amount:'120 g'},{item:'Cucumber, sliced',amount:'1 small'},{item:'Tomato, wedges',amount:'1 medium'},{item:'Red onion, sliced',amount:'¼ cup'},{item:'Lime juice',amount:'2 tbsp'},{item:'Fish sauce',amount:'1 tsp'},{item:'Bird’s eye chilli, sliced',amount:'1'}], instructions:['Combine lettuce, cucumber, tomato and red onion in a bowl.','Mix tuna with lime juice, fish sauce and chilli.','Spoon tuna over the salad and toss gently.','Serve immediately while the vegetables are crisp.'], nutrition:{kcal:220,protein:32,carbs:12,fat:5,fiber:4,sodium:510}, tags:['High protein','Light','No-cook'], accent:'red' }),
  r({ id:'grilled-tilapia-herb-salad', sourceId:'slice1-05', name:'ปลานิลย่างกับสลัดสมุนไพร', englishName:'Grilled Tilapia with Herb Salad', category:'Quick meals', cuisine:'Thai', servings:2, prepMinutes:12, cookMinutes:14, ingredients:[{item:'Tilapia fillets',amount:'320 g'},{item:'Mixed mint and coriander',amount:'1 cup'},{item:'Cucumber, sliced',amount:'1 small'},{item:'Cherry tomatoes, halved',amount:'120 g'},{item:'Lime juice',amount:'2 tbsp'},{item:'Fish sauce',amount:'1 tsp'},{item:'Cooked jasmine rice',amount:'¾ cup'}], instructions:['Pat fish dry and season with a little pepper.','Grill or pan-sear fish for 5–7 minutes per side until it flakes easily.','Toss herbs, cucumber and tomatoes with lime juice and fish sauce.','Serve fish with the herb salad and rice.'], nutrition:{kcal:290,protein:35,carbs:18,fat:8,fiber:3,sodium:500}, tags:['High protein','Light','Gluten-free'], accent:'blue' }),
  r({ id:'chicken-tom-yum-mushrooms', sourceId:'slice1-06', name:'ต้มยำไก่ใส่เห็ดน้ำใส', englishName:'Chicken Tom Yum with Mushrooms', category:'Thai favorites', cuisine:'Thai', servings:2, prepMinutes:12, cookMinutes:15, ingredients:[{item:'Skinless chicken breast, sliced',amount:'260 g'},{item:'Oyster mushrooms, torn',amount:'180 g'},{item:'Tom yum herbs',amount:'1 small bundle'},{item:'Tomato, wedges',amount:'1 medium'},{item:'Lime juice',amount:'2 tbsp'},{item:'Fish sauce',amount:'1 tsp'},{item:'Low-sodium stock',amount:'700 ml'}], instructions:['Simmer stock with tom yum herbs for 5 minutes.','Add chicken and mushrooms; cook gently until chicken is done.','Add tomato and simmer for 2 minutes.','Turn off the heat, season with lime juice and fish sauce, then serve.'], nutrition:{kcal:300,protein:30,carbs:17,fat:12,fiber:4,sodium:560}, tags:['High protein','Light','Gluten-free'], accent:'aqua' }),
  r({ id:'shrimp-lemongrass-salad', sourceId:'slice1-07', name:'ยำกุ้งตะไคร้', englishName:'Shrimp Lemongrass Salad', category:'Light bowls', cuisine:'Thai', servings:2, prepMinutes:15, cookMinutes:6, ingredients:[{item:'Shrimp, peeled',amount:'240 g'},{item:'Lemongrass, finely sliced',amount:'2 stalks'},{item:'Cucumber, sliced',amount:'1 small'},{item:'Mint leaves',amount:'½ cup'},{item:'Roasted peanuts, chopped',amount:'1 tbsp'},{item:'Lime juice',amount:'2 tbsp'},{item:'Fish sauce',amount:'1 tsp'}], instructions:['Poach shrimp in simmering water until pink and opaque, then drain.','Mix lemongrass, cucumber and mint in a bowl.','Whisk lime juice with fish sauce and toss through the salad.','Top with shrimp and peanuts before serving.'], nutrition:{kcal:240,protein:24,carbs:19,fat:7,fiber:4,sodium:530}, tags:['High protein','Light','Gluten-free'], accent:'lime' }),
  r({ id:'lean-pork-pepper-rice', sourceId:'slice1-08', name:'ข้าวหมูพริกไทยดำ', englishName:'Lean Pork Pepper Rice', category:'Quick meals', cuisine:'Thai', servings:2, prepMinutes:10, cookMinutes:14, ingredients:[{item:'Lean pork loin, thinly sliced',amount:'280 g'},{item:'Cooked jasmine rice',amount:'1 cup'},{item:'Onion, sliced',amount:'1 small'},{item:'Bell pepper, sliced',amount:'1'},{item:'Ground black pepper',amount:'1 tsp'},{item:'Light soy sauce',amount:'1 tbsp'},{item:'Spring onion, sliced',amount:'2 stalks'}], instructions:['Season pork with soy sauce and black pepper for 5 minutes.','Stir-fry pork in a hot non-stick pan until almost cooked.','Add onion and bell pepper with 2 tablespoons of water; cook until tender.','Finish with spring onion and serve over rice.'], nutrition:{kcal:450,protein:31,carbs:47,fat:14,fiber:3,sodium:640}, tags:['High protein','Balanced','Quick'], accent:'gold' }),
  r({ id:'chicken-green-curry-brown-rice', sourceId:'slice1-09', name:'แกงเขียวหวานไก่กับข้าวกล้อง', englishName:'Chicken Green Curry with Brown Rice', category:'Thai favorites', cuisine:'Thai', servings:2, prepMinutes:15, cookMinutes:20, ingredients:[{item:'Skinless chicken thigh, sliced',amount:'280 g'},{item:'Light coconut milk',amount:'250 ml'},{item:'Green curry paste',amount:'1½ tbsp'},{item:'Thai eggplant, quartered',amount:'180 g'},{item:'Thai basil',amount:'½ cup'},{item:'Cooked brown rice',amount:'1 cup'},{item:'Fish sauce',amount:'1 tsp'}], instructions:['Simmer curry paste with 3 tablespoons of coconut milk for 2 minutes.','Add chicken and cook until the outside turns opaque.','Pour in remaining coconut milk and add eggplant; simmer until tender.','Season with fish sauce, fold in basil and serve with brown rice.'], nutrition:{kcal:500,protein:33,carbs:47,fat:22,fiber:6,sodium:620}, tags:['High protein','Balanced','Dairy-free'], accent:'lime' }),
  r({ id:'pumpkin-egg-stir-fry', sourceId:'slice1-10', name:'ผัดฟักทองใส่ไข่', englishName:'Pumpkin and Egg Stir-fry', category:'Plant-forward', cuisine:'Thai', servings:2, prepMinutes:10, cookMinutes:14, ingredients:[{item:'Pumpkin, peeled and sliced',amount:'350 g'},{item:'Eggs',amount:'3'},{item:'Firm tofu, cubed',amount:'120 g'},{item:'Thai basil',amount:'½ cup'},{item:'Light soy sauce',amount:'2 tsp'},{item:'Neutral oil',amount:'1 tsp'},{item:'Spring onion, sliced',amount:'2 stalks'}], instructions:['Steam or stir-fry pumpkin with ¼ cup water until nearly tender.','Add tofu and soy sauce, then push everything to one side of the pan.','Scramble eggs in the open space and fold through the pumpkin.','Add basil and spring onion, then serve hot.'], nutrition:{kcal:280,protein:13,carbs:31,fat:12,fiber:5,sodium:470}, tags:['Vegetarian','Fiber-rich','Balanced'], accent:'gold' }),
  r({ id:'chicken-vegetable-sukiyaki', sourceId:'slice1-11', name:'สุกี้น้ำไก่และผัก', englishName:'Chicken and Vegetable Sukiyaki', category:'Quick meals', cuisine:'Thai', servings:2, prepMinutes:15, cookMinutes:14, ingredients:[{item:'Skinless chicken breast, thinly sliced',amount:'260 g'},{item:'Glass noodles, dry',amount:'50 g'},{item:'Chinese cabbage, chopped',amount:'200 g'},{item:'Mushrooms, sliced',amount:'150 g'},{item:'Carrot, sliced',amount:'1 small'},{item:'Low-sodium stock',amount:'700 ml'},{item:'Sukiyaki sauce',amount:'2 tbsp'}], instructions:['Soak glass noodles according to the packet and drain.','Bring stock to a simmer and cook chicken until opaque.','Add cabbage, mushrooms and carrot; simmer until tender.','Add noodles and sukiyaki sauce, warm through and serve.'], nutrition:{kcal:370,protein:35,carbs:32,fat:10,fiber:5,sodium:680}, tags:['High protein','Light','Quick'], accent:'aqua' }),
  r({ id:'spicy-grilled-pork-salad', sourceId:'slice1-12', name:'น้ำตกหมูย่าง', englishName:'Spicy Grilled Pork Salad', category:'Light bowls', cuisine:'Thai', servings:2, prepMinutes:15, cookMinutes:16, ingredients:[{item:'Lean pork tenderloin',amount:'280 g'},{item:'Mint leaves',amount:'½ cup'},{item:'Shallot, sliced',amount:'¼ cup'},{item:'Cabbage, shredded',amount:'180 g'},{item:'Lime juice',amount:'2 tbsp'},{item:'Toasted rice powder',amount:'1 tbsp'},{item:'Fish sauce',amount:'1 tsp'},{item:'Dried chilli flakes',amount:'½ tsp'}], instructions:['Season pork with pepper and grill until cooked through, about 7–8 minutes per side.','Rest for 5 minutes, then slice thinly.','Toss pork with lime juice, fish sauce, toasted rice, shallot and chilli.','Serve over cabbage with mint.'], nutrition:{kcal:330,protein:30,carbs:16,fat:14,fiber:4,sodium:540}, tags:['High protein','Light','Gluten-free'], accent:'red' }),
  r({ id:'chili-lime-chicken-brown-rice', sourceId:'slice1-13', name:'ข้าวกล้องไก่พริกมะนาว', englishName:'Brown Rice with Chili-Lime Chicken', category:'Quick meals', cuisine:'Thai', servings:2, prepMinutes:12, cookMinutes:16, ingredients:[{item:'Skinless chicken breast, sliced',amount:'300 g'},{item:'Brown rice, cooked',amount:'1 cup'},{item:'Green beans, trimmed',amount:'160 g'},{item:'Lime juice',amount:'2 tbsp'},{item:'Bird’s eye chilli, sliced',amount:'1'},{item:'Light soy sauce',amount:'2 tsp'},{item:'Coriander, chopped',amount:'¼ cup'}], instructions:['Marinate chicken with lime juice, chilli and soy sauce for 10 minutes.','Pan-sear chicken until browned and fully cooked.','Steam green beans until crisp-tender.','Serve chicken and beans over brown rice with coriander.'], nutrition:{kcal:430,protein:37,carbs:44,fat:12,fiber:6,sodium:560}, tags:['High protein','Balanced','Meal prep'], accent:'coral' }),
  r({ id:'thai-vegetable-omelet', sourceId:'slice1-14', name:'ไข่เจียวผักกับข้าวกล้อง', englishName:'Thai Vegetable Omelet with Brown Rice', category:'Plant-forward', cuisine:'Thai', servings:2, prepMinutes:10, cookMinutes:10, ingredients:[{item:'Eggs',amount:'4'},{item:'Shiitake mushrooms, sliced',amount:'100 g'},{item:'Tomato, diced',amount:'1 medium'},{item:'Spring onion, sliced',amount:'2 stalks'},{item:'Brown rice, cooked',amount:'¾ cup'},{item:'Light soy sauce',amount:'1 tsp'},{item:'Neutral oil',amount:'1 tsp'}], instructions:['Whisk eggs with soy sauce and fold in mushrooms, tomato and spring onion.','Heat oil in a non-stick pan and pour in the egg mixture.','Cook until the edges set, fold and finish until the centre is firm.','Serve with warm brown rice.'], nutrition:{kcal:310,protein:18,carbs:18,fat:17,fiber:3,sodium:420}, tags:['Vegetarian','Balanced','Quick'], accent:'gold' }),
  r({ id:'tofu-basil-stir-fry', sourceId:'slice1-15', name:'ผัดเต้าหู้กะเพรา', englishName:'Tofu Basil Stir-fry', category:'Plant-forward', cuisine:'Thai', servings:2, prepMinutes:10, cookMinutes:12, ingredients:[{item:'Firm tofu, cubed',amount:'300 g'},{item:'Cooked jasmine rice',amount:'1 cup'},{item:'Thai holy basil',amount:'1 packed cup'},{item:'Long beans, sliced',amount:'120 g'},{item:'Bird’s eye chilli, sliced',amount:'1'},{item:'Light soy sauce',amount:'1 tbsp'},{item:'Sesame oil',amount:'1 tsp'}], instructions:['Pat tofu dry and pan-sear with sesame oil until lightly golden.','Add long beans, chilli and 3 tablespoons of water; cook until tender.','Season with soy sauce and fold in basil until wilted.','Serve over jasmine rice.'], nutrition:{kcal:330,protein:19,carbs:36,fat:12,fiber:5,sodium:560}, tags:['Vegetarian','Plant protein','Quick'], accent:'lime' }),
  r({ id:'chicken-teriyaki-rice-bowl', sourceId:'slice1-16', name:'ข้าวหน้าไก่เทอริยากิ', englishName:'Chicken Teriyaki Rice Bowl', category:'Quick meals', cuisine:'Japanese', servings:2, prepMinutes:12, cookMinutes:15, ingredients:[{item:'Skinless chicken thigh, sliced',amount:'280 g'},{item:'Cooked brown rice',amount:'1 cup'},{item:'Broccoli florets',amount:'180 g'},{item:'Reduced-sodium teriyaki sauce',amount:'2 tbsp'},{item:'Carrot, ribbons',amount:'1 small'},{item:'Sesame seeds',amount:'1 tsp'}], instructions:['Sear chicken in a non-stick pan until browned and cooked through.','Add teriyaki sauce and simmer for 2 minutes until glossy.','Steam broccoli and carrot until tender-crisp.','Serve chicken and vegetables over brown rice with sesame.'], nutrition:{kcal:450,protein:35,carbs:50,fat:12,fiber:6,sodium:650}, tags:['High protein','Balanced','Quick'], accent:'coral' }),
  r({ id:'lean-beef-bibimbap', sourceId:'slice1-17', name:'บิบิมบับเนื้อไม่ติดมัน', englishName:'Lean Beef Bibimbap', category:'High protein', cuisine:'Korean', servings:2, prepMinutes:20, cookMinutes:16, ingredients:[{item:'Lean beef sirloin, thinly sliced',amount:'260 g'},{item:'Brown rice, cooked',amount:'1 cup'},{item:'Eggs',amount:'2'},{item:'Spinach',amount:'120 g'},{item:'Carrot, matchsticks',amount:'1 medium'},{item:'Bean sprouts',amount:'120 g'},{item:'Gochujang',amount:'2 tsp'}], instructions:['Cook beef in a hot pan until just done and set aside.','Sauté spinach, carrot and bean sprouts separately until tender.','Fry eggs to your preferred doneness.','Build bowls with rice, vegetables, beef, egg and gochujang.'], nutrition:{kcal:490,protein:34,carbs:52,fat:16,fiber:7,sodium:610}, tags:['High protein','Balanced','Fiber-rich'], accent:'red' }),
  r({ id:'chicken-soba-bowl', sourceId:'slice1-18', name:'โซบะไก่และผัก', englishName:'Chicken Soba Bowl', category:'Quick meals', cuisine:'Japanese', servings:2, prepMinutes:12, cookMinutes:14, ingredients:[{item:'Skinless chicken breast, sliced',amount:'260 g'},{item:'Buckwheat soba',amount:'140 g'},{item:'Cucumber, sliced',amount:'1 small'},{item:'Edamame, cooked',amount:'100 g'},{item:'Spring onion, sliced',amount:'2 stalks'},{item:'Reduced-sodium soy sauce',amount:'1 tbsp'},{item:'Rice vinegar',amount:'1 tbsp'}], instructions:['Cook soba according to the packet and rinse briefly under cold water.','Pan-sear chicken until cooked through, then slice.','Mix soy sauce, rice vinegar and 2 tablespoons water for dressing.','Divide soba, chicken, edamame and cucumber between bowls and drizzle with dressing.'], nutrition:{kcal:390,protein:31,carbs:47,fat:9,fiber:6,sodium:560}, tags:['High protein','Quick','Dairy-free'], accent:'blue' }),
  r({ id:'salmon-soba-salad', sourceId:'slice1-19', name:'สลัดโซบะแซลมอน', englishName:'Salmon Soba Salad', category:'Light bowls', cuisine:'Japanese', servings:2, prepMinutes:15, cookMinutes:14, ingredients:[{item:'Salmon fillets',amount:'240 g'},{item:'Buckwheat soba',amount:'120 g'},{item:'Cucumber, ribbons',amount:'1 small'},{item:'Edamame, cooked',amount:'80 g'},{item:'Sesame seeds',amount:'1 tsp'},{item:'Rice vinegar',amount:'1 tbsp'},{item:'Reduced-sodium soy sauce',amount:'2 tsp'}], instructions:['Cook soba, rinse under cold water and drain well.','Bake or pan-sear salmon until it flakes, then break into large pieces.','Toss soba with cucumber, edamame, vinegar and soy sauce.','Top with salmon and sesame seeds.'], nutrition:{kcal:410,protein:28,carbs:39,fat:16,fiber:5,sodium:540}, tags:['High protein','Omega-rich','Light'], accent:'aqua' }),
  r({ id:'korean-chicken-lettuce-wraps', sourceId:'slice1-20', name:'ไก่เกาหลีห่อผักกาด', englishName:'Korean Chicken Lettuce Wraps', category:'Light bowls', cuisine:'Korean', servings:2, prepMinutes:15, cookMinutes:14, ingredients:[{item:'Skinless chicken mince',amount:'280 g'},{item:'Butter lettuce leaves',amount:'12 leaves'},{item:'Carrot, matchsticks',amount:'1 small'},{item:'Cucumber, matchsticks',amount:'1 small'},{item:'Gochujang',amount:'1 tbsp'},{item:'Cooked brown rice',amount:'¾ cup'},{item:'Sesame seeds',amount:'1 tsp'}], instructions:['Cook chicken mince in a non-stick pan until no longer pink.','Stir in gochujang and 2 tablespoons of water; simmer until coated.','Arrange lettuce with rice, carrot and cucumber.','Spoon chicken into the leaves and finish with sesame.'], nutrition:{kcal:320,protein:33,carbs:18,fat:13,fiber:4,sodium:590}, tags:['High protein','Light','Gluten-free'], accent:'lime' }),
  r({ id:'tuna-onigiri-plate', sourceId:'slice1-21', name:'ชุดโอนิกิริทูน่า', englishName:'Tuna Onigiri Plate', category:'Quick meals', cuisine:'Japanese', servings:2, prepMinutes:20, cookMinutes:5, ingredients:[{item:'Cooked sushi rice',amount:'1½ cups'},{item:'Tuna in spring water, drained',amount:'160 g'},{item:'Nori sheets',amount:'2'},{item:'Cucumber, sliced',amount:'1 small'},{item:'Edamame, cooked',amount:'100 g'},{item:'Light mayonnaise',amount:'1 tbsp'},{item:'Rice vinegar',amount:'1 tsp'}], instructions:['Mix tuna with light mayonnaise and rice vinegar.','Wet hands, fill rice with tuna and shape into four triangles.','Wrap each onigiri with nori just before eating.','Serve with cucumber and edamame.'], nutrition:{kcal:360,protein:26,carbs:49,fat:8,fiber:4,sodium:520}, tags:['High protein','Meal prep','Dairy-free'], accent:'blue' }),
  r({ id:'miso-salmon-vegetables', sourceId:'slice1-22', name:'แซลมอนมิโสะกับผักย่าง', englishName:'Miso Salmon with Vegetables', category:'High protein', cuisine:'Japanese', servings:2, prepMinutes:12, cookMinutes:16, ingredients:[{item:'Salmon fillets',amount:'280 g'},{item:'White miso',amount:'1 tbsp'},{item:'Broccoli florets',amount:'180 g'},{item:'Sweet potato, cubed',amount:'220 g'},{item:'Sesame seeds',amount:'1 tsp'},{item:'Lime juice',amount:'1 tbsp'}], instructions:['Mix miso with lime juice and brush over salmon.','Roast sweet potato at 200°C until nearly tender, about 12 minutes.','Add salmon and broccoli to the tray and roast until salmon flakes.','Sprinkle with sesame and serve.'], nutrition:{kcal:430,protein:31,carbs:25,fat:23,fiber:6,sodium:620}, tags:['High protein','Omega-rich','Balanced'], accent:'gold' }),
  r({ id:'tofu-mushroom-rice-bowl', sourceId:'slice1-23', name:'ข้าวหน้าเต้าหู้เห็ด', englishName:'Tofu Mushroom Rice Bowl', category:'Plant-forward', cuisine:'Japanese', servings:2, prepMinutes:12, cookMinutes:14, ingredients:[{item:'Firm tofu, cubed',amount:'300 g'},{item:'Cooked brown rice',amount:'1 cup'},{item:'Shiitake mushrooms, sliced',amount:'160 g'},{item:'Bok choy, chopped',amount:'180 g'},{item:'Reduced-sodium soy sauce',amount:'1 tbsp'},{item:'Ginger, grated',amount:'1 tsp'},{item:'Sesame seeds',amount:'1 tsp'}], instructions:['Pan-sear tofu until lightly golden on two sides.','Add mushrooms, ginger and 2 tablespoons of water; cook until soft.','Stir in soy sauce and bok choy, cooking until wilted.','Serve over brown rice with sesame seeds.'], nutrition:{kcal:390,protein:20,carbs:49,fat:12,fiber:7,sodium:580}, tags:['Vegetarian','Plant protein','Fiber-rich'], accent:'violet' }),
  r({ id:'tofu-egg-donburi', sourceId:'slice1-24', name:'ข้าวหน้าเต้าหู้และไข่', englishName:'Tofu and Egg Donburi', category:'Plant-forward', cuisine:'Japanese', servings:2, prepMinutes:10, cookMinutes:15, ingredients:[{item:'Firm tofu, cubed',amount:'220 g'},{item:'Eggs',amount:'3'},{item:'Cooked brown rice',amount:'1 cup'},{item:'Onion, thinly sliced',amount:'1 small'},{item:'Spinach',amount:'100 g'},{item:'Reduced-sodium soy sauce',amount:'1 tbsp'},{item:'Dashi stock',amount:'200 ml'}], instructions:['Simmer onion in dashi and soy sauce until translucent.','Add tofu and spinach and warm through.','Pour in beaten eggs, cover and cook until softly set.','Spoon over brown rice and serve.'], nutrition:{kcal:400,protein:23,carbs:50,fat:13,fiber:5,sodium:590}, tags:['Vegetarian','Balanced','Quick'], accent:'aqua' }),
  r({ id:'korean-tofu-glass-noodles', sourceId:'slice1-25', name:'วุ้นเส้นเกาหลีเต้าหู้และผัก', englishName:'Korean Tofu Glass Noodles', category:'Plant-forward', cuisine:'Korean', servings:2, prepMinutes:15, cookMinutes:14, ingredients:[{item:'Firm tofu, sliced',amount:'260 g'},{item:'Glass noodles, dry',amount:'90 g'},{item:'Spinach',amount:'120 g'},{item:'Carrot, matchsticks',amount:'1 medium'},{item:'Shiitake mushrooms, sliced',amount:'120 g'},{item:'Reduced-sodium soy sauce',amount:'1 tbsp'},{item:'Sesame oil',amount:'1 tsp'}], instructions:['Soak or cook glass noodles according to the packet and drain.','Pan-sear tofu until golden, then set aside.','Stir-fry carrot, mushrooms and spinach until tender.','Toss noodles and soy sauce through the vegetables, then top with tofu and sesame oil.'], nutrition:{kcal:350,protein:18,carbs:51,fat:9,fiber:6,sodium:570}, tags:['Vegetarian','Plant protein','Fiber-rich'], accent:'red' }),
  r({ id:'grilled-chicken-caesar-salad', sourceId:'slice1-26', name:'ซีซาร์สลัดไก่ย่าง', englishName:'Grilled Chicken Caesar Salad', category:'Light bowls', cuisine:'American', servings:2, prepMinutes:15, cookMinutes:16, ingredients:[{item:'Skinless chicken breast',amount:'280 g'},{item:'Romaine lettuce, chopped',amount:'240 g'},{item:'Whole-wheat bread, cubed',amount:'2 slices'},{item:'Parmesan, grated',amount:'20 g'},{item:'Greek yogurt',amount:'2 tbsp'},{item:'Lemon juice',amount:'1 tbsp'},{item:'Olive oil',amount:'1 tsp'}], instructions:['Grill chicken until cooked through, rest for 5 minutes and slice.','Toast bread cubes in a dry pan until crisp.','Mix yogurt, lemon juice and olive oil into a light dressing.','Toss lettuce with dressing, top with chicken, croutons and parmesan.'], nutrition:{kcal:390,protein:37,carbs:16,fat:19,fiber:4,sodium:620}, tags:['High protein','Light','Balanced'], accent:'lime' }),
  r({ id:'chicken-avocado-wrap', sourceId:'slice1-27', name:'แรปไก่อะโวคาโด', englishName:'Chicken Avocado Wrap', category:'Quick meals', cuisine:'Mexican-inspired', servings:2, prepMinutes:15, cookMinutes:12, ingredients:[{item:'Skinless chicken breast, sliced',amount:'260 g'},{item:'Whole-wheat tortillas',amount:'2 medium'},{item:'Avocado, sliced',amount:'½'},{item:'Tomato, diced',amount:'1 medium'},{item:'Lettuce, shredded',amount:'1 cup'},{item:'Greek yogurt',amount:'2 tbsp'},{item:'Lime juice',amount:'1 tbsp'}], instructions:['Pan-sear chicken until cooked through and slice thinly.','Mix yogurt with lime juice for a quick dressing.','Layer tortillas with lettuce, chicken, tomato and avocado.','Drizzle with dressing, roll tightly and cut in half.'], nutrition:{kcal:440,protein:32,carbs:39,fat:17,fiber:8,sodium:570}, tags:['High protein','Balanced','Quick'], accent:'gold' }),
  r({ id:'tuna-whole-wheat-sandwich', sourceId:'slice1-28', name:'แซนด์วิชทูน่าโฮลวีต', englishName:'Tuna Whole-Wheat Sandwich', category:'Quick meals', cuisine:'American', servings:2, prepMinutes:10, cookMinutes:0, ingredients:[{item:'Tuna in spring water, drained',amount:'180 g'},{item:'Whole-wheat bread',amount:'4 slices'},{item:'Greek yogurt',amount:'3 tbsp'},{item:'Celery, finely diced',amount:'½ cup'},{item:'Cucumber, sliced',amount:'1 small'},{item:'Lettuce leaves',amount:'4'},{item:'Lemon juice',amount:'1 tbsp'}], instructions:['Mix tuna with yogurt, celery and lemon juice.','Place lettuce and cucumber on two bread slices.','Spoon over the tuna mixture and close with remaining bread.','Cut each sandwich in half and serve chilled.'], nutrition:{kcal:360,protein:29,carbs:38,fat:11,fiber:7,sodium:590}, tags:['High protein','Quick','Meal prep'], accent:'blue' }),
  r({ id:'shrimp-tomato-pasta', sourceId:'slice1-29', name:'พาสต้ากุ้งซอสมะเขือเทศ', englishName:'Shrimp Tomato Pasta', category:'Quick meals', cuisine:'Italian', servings:2, prepMinutes:10, cookMinutes:16, ingredients:[{item:'Whole-wheat spaghetti, dry',amount:'150 g'},{item:'Shrimp, peeled',amount:'240 g'},{item:'Crushed tomatoes',amount:'300 g'},{item:'Spinach',amount:'100 g'},{item:'Olive oil',amount:'1 tsp'},{item:'Chilli flakes',amount:'½ tsp'},{item:'Basil leaves',amount:'½ cup'}], instructions:['Cook pasta until just tender, reserving ½ cup cooking water.','Warm oil and chilli flakes, then add tomatoes and simmer for 8 minutes.','Add shrimp and spinach; cook until shrimp are opaque.','Toss with pasta and enough cooking water to loosen, then add basil.'], nutrition:{kcal:430,protein:29,carbs:56,fat:10,fiber:9,sodium:520}, tags:['High protein','Quick','Dairy-free'], accent:'red' }),
  r({ id:'chicken-pesto-pasta', sourceId:'slice1-30', name:'พาสต้าไก่เพสโต้', englishName:'Chicken Pesto Pasta', category:'Quick meals', cuisine:'Italian', servings:2, prepMinutes:10, cookMinutes:18, ingredients:[{item:'Skinless chicken breast, diced',amount:'260 g'},{item:'Whole-wheat penne, dry',amount:'150 g'},{item:'Basil pesto',amount:'2 tbsp'},{item:'Cherry tomatoes, halved',amount:'150 g'},{item:'Spinach',amount:'100 g'},{item:'Parmesan, grated',amount:'15 g'}], instructions:['Cook pasta until tender and reserve ½ cup cooking water.','Pan-sear chicken until fully cooked.','Add tomatoes and spinach to the pan until softened.','Toss chicken, vegetables and pasta with pesto and a splash of cooking water.'], nutrition:{kcal:510,protein:34,carbs:55,fat:18,fiber:8,sodium:650}, tags:['High protein','Balanced','Quick'], accent:'aqua' }),
  r({ id:'lean-beef-burrito-bowl', sourceId:'slice1-31', name:'โบวล์เบอร์ริโตเนื้อไม่ติดมัน', englishName:'Lean Beef Burrito Bowl', category:'High protein', cuisine:'Mexican', servings:2, prepMinutes:15, cookMinutes:16, ingredients:[{item:'Lean beef mince',amount:'260 g'},{item:'Brown rice, cooked',amount:'1 cup'},{item:'Black beans, rinsed',amount:'1 cup'},{item:'Corn kernels',amount:'½ cup'},{item:'Tomato salsa',amount:'½ cup'},{item:'Avocado, sliced',amount:'½'},{item:'Lime juice',amount:'1 tbsp'}], instructions:['Cook beef mince in a non-stick pan until browned and fully cooked.','Warm black beans and corn together.','Divide rice between bowls and add beef, beans, corn and salsa.','Top with avocado and lime juice.'], nutrition:{kcal:520,protein:36,carbs:57,fat:16,fiber:12,sodium:610}, tags:['High protein','Fiber-rich','Balanced'], accent:'gold' }),
  r({ id:'mediterranean-chicken-bowl', sourceId:'slice1-32', name:'โบวล์ไก่เมดิเตอร์เรเนียน', englishName:'Mediterranean Chicken Bowl', category:'Light bowls', cuisine:'Mediterranean', servings:2, prepMinutes:18, cookMinutes:16, ingredients:[{item:'Skinless chicken breast, sliced',amount:'280 g'},{item:'Cooked quinoa',amount:'1 cup'},{item:'Cucumber, diced',amount:'1 small'},{item:'Cherry tomatoes, halved',amount:'150 g'},{item:'Chickpeas, rinsed',amount:'½ cup'},{item:'Greek yogurt',amount:'3 tbsp'},{item:'Lemon juice',amount:'1 tbsp'}], instructions:['Season chicken with pepper and grill or pan-sear until cooked through.','Mix yogurt with lemon juice for a simple sauce.','Divide quinoa, cucumber, tomatoes and chickpeas between bowls.','Top with sliced chicken and yogurt sauce.'], nutrition:{kcal:460,protein:36,carbs:42,fat:16,fiber:9,sodium:480}, tags:['High protein','Balanced','Meal prep'], accent:'lime' }),
  r({ id:'chickpea-mediterranean-salad', sourceId:'slice1-33', name:'สลัดถั่วชิกพีเมดิเตอร์เรเนียน', englishName:'Chickpea Mediterranean Salad', category:'Plant-forward', cuisine:'Mediterranean', servings:2, prepMinutes:15, cookMinutes:0, ingredients:[{item:'Chickpeas, rinsed',amount:'1½ cups'},{item:'Cucumber, diced',amount:'1 large'},{item:'Tomatoes, diced',amount:'2 medium'},{item:'Red onion, sliced',amount:'¼ cup'},{item:'Feta cheese, crumbled',amount:'40 g'},{item:'Olive oil',amount:'1 tsp'},{item:'Lemon juice',amount:'2 tbsp'}], instructions:['Combine chickpeas, cucumber, tomatoes and red onion.','Whisk olive oil with lemon juice and black pepper.','Toss dressing through the salad.','Scatter with feta and serve chilled or at room temperature.'], nutrition:{kcal:350,protein:14,carbs:45,fat:12,fiber:12,sodium:470}, tags:['Vegetarian','Fiber-rich','No-cook'], accent:'aqua' }),
  r({ id:'pumpkin-soup-with-egg', sourceId:'slice1-34', name:'ซุปฟักทองกับไข่ต้ม', englishName:'Pumpkin Soup with Egg', category:'Light bowls', cuisine:'International', servings:2, prepMinutes:12, cookMinutes:22, ingredients:[{item:'Pumpkin, peeled and cubed',amount:'450 g'},{item:'Eggs',amount:'2'},{item:'Low-sodium vegetable stock',amount:'600 ml'},{item:'Plain Greek yogurt',amount:'2 tbsp'},{item:'Onion, chopped',amount:'1 small'},{item:'Pumpkin seeds',amount:'1 tbsp'}], instructions:['Simmer pumpkin, onion and stock until the pumpkin is very tender.','Blend until smooth, then return to the pot and warm gently.','Boil eggs for 8–9 minutes, cool, peel and halve.','Serve soup with egg, yogurt and pumpkin seeds.'], nutrition:{kcal:280,protein:13,carbs:34,fat:10,fiber:7,sodium:430}, tags:['Vegetarian','Light','Fiber-rich'], accent:'gold' }),
  r({ id:'egg-avocado-toast', sourceId:'slice1-35', name:'ขนมปังโฮลวีตไข่อะโวคาโด', englishName:'Egg and Avocado Toast', category:'Quick meals', cuisine:'International', servings:2, prepMinutes:8, cookMinutes:8, ingredients:[{item:'Whole-wheat bread',amount:'4 slices'},{item:'Eggs',amount:'4'},{item:'Avocado',amount:'1 medium'},{item:'Cherry tomatoes, halved',amount:'120 g'},{item:'Lime juice',amount:'1 tbsp'},{item:'Pumpkin seeds',amount:'1 tbsp'}], instructions:['Toast the bread until crisp.','Mash avocado with lime juice and spread over the toast.','Poach or soft-boil eggs until the whites are set.','Top toast with egg, tomatoes and pumpkin seeds.'], nutrition:{kcal:380,protein:17,carbs:35,fat:19,fiber:9,sodium:390}, tags:['Vegetarian','Balanced','Quick'], accent:'coral' }),
  ...recipeExpansionSeeds.map(recipe => r(recipe))
]

export function filterRecipes(items: Recipe[], filters: Filters): Recipe[] {
  const queryCategory = filters.category
  return items.filter(recipe =>
    (!queryCategory || recipe.category === queryCategory) &&
    (filters.maxKcal === undefined || recipe.nutrition.kcal <= filters.maxKcal) &&
    (filters.minProtein === undefined || recipe.nutrition.protein >= filters.minProtein) &&
    (filters.maxCarbs === undefined || recipe.nutrition.carbs <= filters.maxCarbs) &&
    (filters.maxFat === undefined || recipe.nutrition.fat <= filters.maxFat) &&
    (filters.maxSodium === undefined || (recipe.nutrition.sodium !== undefined && recipe.nutrition.sodium <= filters.maxSodium)) &&
    filters.tags.every(tag => recipe.tags.includes(tag))
  )
}

export function searchRecipes(items: Recipe[], rawQuery: string): Recipe[] {
  const query = rawQuery.trim().toLocaleLowerCase()
  if (!query) return items
  return items.filter(recipe => [recipe.name.th, recipe.name.en, recipe.category, recipe.cuisine.th, recipe.cuisine.en, ...recipe.tags, ...recipe.ingredients.flatMap(ingredient => [ingredient.item.th, ingredient.item.en]), ...recipe.instructions.flatMap(instruction => [instruction.th, instruction.en])].join(' ').toLocaleLowerCase().includes(query))
}

export function chooseRandom(items: Recipe[], previousId?: string, random = Math.random): Recipe | undefined {
  if (!items.length) return undefined
  const choices = items.length > 1 && previousId ? items.filter(item => item.id !== previousId) : items
  return choices[Math.floor(random() * choices.length)]
}

export function validateRecipes(items: Recipe[]): string[] {
  const errors: string[] = []
  if (!Array.isArray(items)) return ['Invalid recipe array']
  const ids = new Set<string>()
  const names = new Set<string>()
  const images = new Set<string>()
  const categories = new Set<Recipe['category']>(['Quick meals', 'Thai favorites', 'High protein', 'Plant-forward', 'Light bowls'])
  const hasText = (value: unknown): value is string => typeof value === 'string' && value.trim().length > 0
  const hasLocalizedText = (value: unknown): value is LocalizedText => typeof value === 'object' && value !== null && hasText((value as Record<string, unknown>).th) && hasText((value as Record<string, unknown>).en)
  const hasQuantity = (value: unknown): value is string | number => (typeof value === 'string' && value.trim().length > 0) || (typeof value === 'number' && Number.isFinite(value))
  const hasNutrition = (value: unknown): value is Record<string, number> => typeof value === 'object' && value !== null && ['kcal', 'protein', 'carbs', 'fat'].every(key => typeof (value as Record<string, unknown>)[key] === 'number' && Number.isFinite((value as Record<string, number>)[key]) && (value as Record<string, number>)[key] >= 0) && Object.values(value).every(number => typeof number === 'number' && Number.isFinite(number) && number >= 0)
  for (const rawRecipe of items) {
    const recipe = (rawRecipe && typeof rawRecipe === 'object' ? rawRecipe : {}) as Partial<Recipe>
    const id = hasText(recipe.id) ? recipe.id : '(missing id)'
    const ingredients = Array.isArray(recipe.ingredients) ? recipe.ingredients : []
    const instructions = Array.isArray(recipe.instructions) ? recipe.instructions : []
    if (ids.has(id)) errors.push(`Duplicate id: ${id}`)
    if (hasLocalizedText(recipe.name) && (names.has(recipe.name.th) || names.has(recipe.name.en))) errors.push(`Duplicate name: ${recipe.name.en}`)
    if (hasText(recipe.image) && images.has(recipe.image)) errors.push(`Duplicate image: ${recipe.image}`)
    ids.add(id)
    if (hasLocalizedText(recipe.name)) { names.add(recipe.name.th); names.add(recipe.name.en) }
    if (hasText(recipe.image)) images.add(recipe.image)
    if (!hasText(recipe.id) || !hasLocalizedText(recipe.name) || !hasLocalizedText(recipe.cuisine) || !ingredients.length || !instructions.length || ingredients.some(ingredient => !hasLocalizedText(ingredient?.item) || !hasQuantity(ingredient?.quantity)) || instructions.some(step => !hasLocalizedText(step))) errors.push(`Missing required content: ${id}`)
    if (!hasLocalizedText(recipe.name) || !hasText(recipe.name.th)) errors.push(`Missing Thai name: ${id}`)
    if (!hasLocalizedText(recipe.name) || !hasText(recipe.name.en)) errors.push(`Missing English name: ${id}`)
    if (!ingredients.length || ingredients.some(ingredient => !hasLocalizedText(ingredient?.item) || !hasText(ingredient?.item?.th))) errors.push(`Missing Thai ingredients: ${id}`)
    if (!ingredients.length || ingredients.some(ingredient => !hasLocalizedText(ingredient?.item) || !hasText(ingredient?.item?.en))) errors.push(`Missing English ingredients: ${id}`)
    if (!ingredients.length || ingredients.some(ingredient => !hasQuantity(ingredient?.quantity))) errors.push(`Missing ingredient quantity: ${id}`)
    if (ingredients.some(ingredient => hasQuantity(ingredient?.quantity) && !isValidIngredientQuantity(ingredient.quantity))) errors.push(`Invalid ingredient quantity: ${id}`)
    if (ingredients.some(ingredient => ingredient?.unit !== undefined && !isIngredientUnit(ingredient.unit))) errors.push(`Unknown ingredient unit: ${id}`)
    if (ingredients.some(ingredient => ingredient?.ingredientId !== undefined && !canonicalIngredientIds.has(ingredient.ingredientId))) errors.push(`Unknown pantry ingredient: ${id}`)
    if (!instructions.length || instructions.some(step => !hasLocalizedText(step) || !hasText(step?.th))) errors.push(`Missing Thai instructions: ${id}`)
    if (!instructions.length || instructions.some(step => !hasLocalizedText(step) || !hasText(step?.en))) errors.push(`Missing English instructions: ${id}`)
    if (!categories.has(recipe.category as Recipe['category'])) errors.push(`Invalid category: ${id}`)
    if (!hasText(recipe.image) || !/^\/recipes\/[a-z0-9]+(?:-[a-z0-9]+)*\.webp$/.test(recipe.image)) errors.push(`Invalid image path: ${id}`)
    const servings = recipe.servings ?? Number.NaN
    const prepMinutes = recipe.prepMinutes ?? Number.NaN
    const cookMinutes = recipe.cookMinutes ?? Number.NaN
    if (!Number.isInteger(servings) || servings <= 0 || !Number.isFinite(prepMinutes) || !Number.isFinite(cookMinutes) || prepMinutes < 0 || cookMinutes < 0) errors.push(`Invalid timing or servings: ${id}`)
    if (!hasNutrition(recipe.nutrition)) errors.push(`Invalid nutrition: ${id}`)
    else {
      const macroKcal = recipe.nutrition.protein * 4 + recipe.nutrition.carbs * 4 + recipe.nutrition.fat * 9
      if (Math.abs(recipe.nutrition.kcal - macroKcal) > 180) errors.push(`Nutrition sanity range: ${id}`)
    }
  }
  return errors
}
