import type { Filters, Recipe } from './types'

export const emptyFilters: Filters = { category: '', tags: [] }

const r = (recipe: Recipe) => recipe

export const recipes: Recipe[] = [
  r({ id:'tom-yum-prawns', sourceId:'f002', name:'ต้มยำกุ้งน้ำใส', englishName:'Clear Tom Yum Prawns', category:'Thai favorites', cuisine:'Thai', servings:2, prepMinutes:12, cookMinutes:10, ingredients:[{item:'Prawns, peeled',amount:'220 g'},{item:'Mushrooms, halved',amount:'150 g'},{item:'Tom yum herbs (lemongrass, galangal, lime leaves)',amount:'1 small bundle'},{item:'Cherry tomatoes',amount:'120 g'},{item:'Lime juice',amount:'2 tbsp'},{item:'Fish sauce',amount:'1½ tsp'}], instructions:['Bring 700 ml water to a gentle simmer with the tom yum herbs for 4 minutes.','Add mushrooms and tomatoes; cook until just softened.','Add prawns and poach until opaque, 2–3 minutes. Turn off the heat.','Season with lime juice and fish sauce, tasting before adding more salt.'], nutrition:{kcal:150,protein:16,carbs:9,fat:3,fiber:3,sodium:360}, tags:['High protein','Light','Gluten-free'], accent:'coral' }),
  r({ id:'glass-noodle-seafood-salad', sourceId:'f008', name:'ยำวุ้นเส้นทะเล', englishName:'Glass Noodle Seafood Salad', category:'Light bowls', cuisine:'Thai', servings:2, prepMinutes:15, cookMinutes:8, ingredients:[{item:'Glass noodles, dry',amount:'70 g'},{item:'Mixed seafood',amount:'220 g'},{item:'Tomato, wedges',amount:'1 medium'},{item:'Red onion, sliced',amount:'¼ cup'},{item:'Celery, sliced',amount:'½ cup'},{item:'Lime juice',amount:'2 tbsp'},{item:'Fish sauce',amount:'1 tsp'}], instructions:['Soak or cook noodles according to the packet, then cool briefly.','Poach seafood in simmering water until cooked through, then drain.','Toss noodles, seafood, tomato, onion and celery.','Dress with lime juice and fish sauce just before serving.'], nutrition:{kcal:220,protein:18,carbs:25,fat:6,fiber:3,sodium:690}, tags:['High protein','Light','Dairy-free'], accent:'lime' }),
  r({ id:'tofu-mince-soup', sourceId:'f038', name:'แกงจืดเต้าหู้หมูสับ', englishName:'Tofu & Pork Mince Soup', category:'Thai favorites', cuisine:'Thai', servings:2, prepMinutes:10, cookMinutes:15, ingredients:[{item:'Lean pork mince',amount:'180 g'},{item:'Firm tofu, cubed',amount:'200 g'},{item:'Chinese cabbage, chopped',amount:'180 g'},{item:'Coriander root and garlic, pounded',amount:'1 tsp'},{item:'Low-sodium stock',amount:'750 ml'},{item:'Light soy sauce',amount:'1 tsp'}], instructions:['Mix pork with the pounded coriander root and garlic; form small balls.','Bring stock to a simmer and add pork balls for 5 minutes.','Add cabbage and tofu; simmer gently until the cabbage is tender.','Season lightly with soy sauce and finish with coriander.'], nutrition:{kcal:240,protein:25,carbs:10,fat:11,fiber:3,sodium:610}, tags:['Comforting','High protein','Low carb'], accent:'violet' }),
  r({ id:'herb-grilled-chicken', sourceId:'f042', name:'ไก่ย่างสมุนไพรกับผัก', englishName:'Herb Grilled Chicken & Vegetables', category:'High protein', cuisine:'Thai', servings:2, prepMinutes:15, cookMinutes:18, ingredients:[{item:'Skinless chicken thighs',amount:'300 g'},{item:'Garlic, grated',amount:'2 cloves'},{item:'Coriander root, pounded',amount:'1 tsp'},{item:'Broccoli florets',amount:'180 g'},{item:'Carrot, sliced',amount:'1 medium'},{item:'Brown rice, cooked',amount:'1 cup'}], instructions:['Rub chicken with garlic and coriander root; rest for 10 minutes.','Grill or pan-sear chicken until the centre is fully cooked, about 6–8 minutes per side.','Steam broccoli and carrot until crisp-tender.','Slice chicken and serve with vegetables and brown rice.'], nutrition:{kcal:420,protein:40,carbs:34,fat:14,fiber:6,sodium:480}, tags:['High protein','Meal prep','Gluten-free'], accent:'gold' }),
  r({ id:'cold-soba-edamame', sourceId:'f076', name:'โซบะเย็นเอเดมาเมะ', englishName:'Cold Soba with Edamame', category:'Quick meals', cuisine:'Japanese', servings:2, prepMinutes:10, cookMinutes:8, ingredients:[{item:'Buckwheat soba',amount:'150 g'},{item:'Shelled edamame',amount:'120 g'},{item:'Cucumber, ribbons',amount:'1 small'},{item:'Carrot, julienned',amount:'1 small'},{item:'Reduced-sodium soy sauce',amount:'1 tbsp'},{item:'Rice vinegar',amount:'1 tbsp'}], instructions:['Cook soba until tender and rinse under cold water.','Steam edamame for 3 minutes and cool.','Whisk soy sauce with rice vinegar and 2 tbsp water.','Toss noodles, vegetables and edamame with dressing.'], nutrition:{kcal:350,protein:16,carbs:58,fat:6,fiber:7,sodium:520}, tags:['Plant protein','Quick','Dairy-free'], accent:'blue' }),
  r({ id:'salmon-teriyaki-bowl', sourceId:'f079', name:'แซลมอนย่างเทอริยากิ', englishName:'Lighter Teriyaki Salmon Bowl', category:'High protein', cuisine:'Japanese', servings:2, prepMinutes:12, cookMinutes:15, ingredients:[{item:'Salmon fillets',amount:'280 g'},{item:'Reduced-sodium teriyaki sauce',amount:'1½ tbsp'},{item:'Brown rice, cooked',amount:'1 cup'},{item:'Broccoli',amount:'200 g'},{item:'Sesame seeds',amount:'1 tsp'}], instructions:['Brush salmon with half the sauce.','Bake or pan-sear salmon until it flakes easily, 10–12 minutes.','Steam broccoli until bright green and tender.','Serve with rice, broccoli, remaining sauce and sesame.'], nutrition:{kcal:480,protein:32,carbs:40,fat:22,fiber:6,sodium:680}, tags:['High protein','Omega-rich','Meal prep'], accent:'coral' }),
  r({ id:'veggie-bibimbap', sourceId:'f117', name:'ข้าวยำเกาหลีผักและไข่', englishName:'Vegetable Bibimbap with Egg', category:'Plant-forward', cuisine:'Korean', servings:2, prepMinutes:20, cookMinutes:15, ingredients:[{item:'Brown rice, cooked',amount:'1½ cups'},{item:'Eggs',amount:'2'},{item:'Spinach',amount:'120 g'},{item:'Carrot, matchsticks',amount:'1 medium'},{item:'Mushrooms, sliced',amount:'150 g'},{item:'Gochujang',amount:'2 tsp'}], instructions:['Sauté mushrooms and carrots separately with a splash of water.','Wilt spinach in a hot pan and season lightly.','Fry eggs to your preferred doneness.','Build bowls with rice, vegetables, egg and a small spoonful of gochujang.'], nutrition:{kcal:420,protein:16,carbs:60,fat:12,fiber:8,sodium:570}, tags:['Vegetarian','Fiber-rich','Balanced'], accent:'red' }),
  r({ id:'mango-vietnamese-salad', sourceId:'f134', name:'สลัดเวียดนามยำมะม่วง', englishName:'Vietnamese Mango Herb Salad', category:'Light bowls', cuisine:'Vietnamese', servings:2, prepMinutes:18, cookMinutes:0, ingredients:[{item:'Green mango, julienned',amount:'1 medium'},{item:'Cucumber, ribbons',amount:'1 small'},{item:'Mint and coriander',amount:'1 cup'},{item:'Roasted peanuts, chopped',amount:'1 tbsp'},{item:'Lime juice',amount:'2 tbsp'},{item:'Fish sauce',amount:'1 tsp'}], instructions:['Combine mango, cucumber and herbs in a wide bowl.','Mix lime juice with fish sauce and 1 tbsp water.','Toss the salad with dressing immediately before serving.','Scatter with peanuts.'], nutrition:{kcal:150,protein:6,carbs:22,fat:4,fiber:5,sodium:390}, tags:['Light','No-cook','Dairy-free'], accent:'gold' }),
  r({ id:'steamed-lime-seabass', sourceId:'f194', name:'ปลากะพงนึ่งมะนาว', englishName:'Steamed Lime Sea Bass', category:'Thai favorites', cuisine:'Thai', servings:2, prepMinutes:15, cookMinutes:15, ingredients:[{item:'Sea bass fillets',amount:'300 g'},{item:'Garlic, minced',amount:'3 cloves'},{item:'Lime juice',amount:'3 tbsp'},{item:'Bird’s eye chilli, sliced',amount:'1–2'},{item:'Chinese celery',amount:'½ cup'},{item:'Jasmine rice, cooked',amount:'1 cup'}], instructions:['Place fish on a heatproof plate and steam until opaque, 12–15 minutes.','Mix garlic, lime juice, chilli and 2 tbsp warm water.','Spoon sauce over the cooked fish and top with celery.','Serve with rice and extra vegetables.'], nutrition:{kcal:285,protein:34,carbs:28,fat:4,fiber:2,sodium:620}, tags:['High protein','Gluten-free','Light'], accent:'aqua' }),
  r({ id:'prawn-rice-congee', sourceId:'f241', name:'ข้าวต้มกุ้งขิง', englishName:'Ginger Prawn Rice Congee', category:'Quick meals', cuisine:'Thai', servings:2, prepMinutes:8, cookMinutes:20, ingredients:[{item:'Cooked jasmine rice',amount:'1½ cups'},{item:'Prawns, peeled',amount:'180 g'},{item:'Ginger, julienned',amount:'1 tbsp'},{item:'Mushrooms, sliced',amount:'120 g'},{item:'Low-sodium stock',amount:'750 ml'},{item:'Spring onion',amount:'2 stalks'}], instructions:['Simmer rice and stock for 15 minutes, stirring until porridge-like.','Add ginger and mushrooms; cook 3 minutes.','Add prawns and cook until opaque.','Top with spring onion and season sparingly.'], nutrition:{kcal:260,protein:18,carbs:35,fat:5,fiber:3,sodium:560}, tags:['Comforting','High protein','Low fat'], accent:'violet' }),
  r({ id:'gazpacho-chickpea', sourceId:'f259', name:'กัซปาโชถั่วชิกพี', englishName:'Gazpacho with Chickpeas', category:'Plant-forward', cuisine:'Spanish', servings:2, prepMinutes:15, cookMinutes:0, ingredients:[{item:'Ripe tomatoes, chopped',amount:'500 g'},{item:'Cucumber, chopped',amount:'½ large'},{item:'Red bell pepper',amount:'1'},{item:'Chickpeas, rinsed',amount:'1 cup'},{item:'Olive oil',amount:'1 tsp'},{item:'Red wine vinegar',amount:'1 tbsp'}], instructions:['Blend tomatoes, cucumber, pepper, vinegar and olive oil until smooth.','Chill for 10 minutes if time allows.','Divide into bowls and top with chickpeas.','Season with black pepper and fresh herbs.'], nutrition:{kcal:240,protein:9,carbs:36,fat:7,fiber:10,sodium:320}, tags:['Vegan','No-cook','Fiber-rich'], accent:'red' }),
  r({ id:'salmon-poke-bowl', sourceId:'f270', name:'โพเกโบวล์แซลมอน', englishName:'Salmon Poke Bowl', category:'Light bowls', cuisine:'Hawaiian', servings:2, prepMinutes:18, cookMinutes:0, ingredients:[{item:'Sushi-grade salmon, cubed and kept chilled',amount:'220 g'},{item:'Brown rice, cooked',amount:'1 cup'},{item:'Edamame, cooked',amount:'100 g'},{item:'Cucumber, cubed',amount:'1 small'},{item:'Avocado, sliced',amount:'½'},{item:'Lime juice',amount:'1 tbsp'},{item:'Reduced-sodium soy sauce',amount:'2 tsp'}], instructions:['Place chilled sushi-grade salmon in a bowl with soy sauce and lime juice.','Divide rice, cooked edamame, cucumber and avocado between bowls.','Add salmon to each bowl.','Finish with sesame or nori if desired.'], nutrition:{kcal:480,protein:28,carbs:50,fat:18,fiber:8,sodium:510}, tags:['High protein','Omega-rich','No-cook'], accent:'aqua' }),
  r({ id:'grilled-mackerel-bowl', sourceId:'f297', name:'ปลาซาบะย่างกับข้าวกล้อง', englishName:'Grilled Mackerel Brown Rice Bowl', category:'High protein', cuisine:'Japanese', servings:2, prepMinutes:10, cookMinutes:15, ingredients:[{item:'Mackerel fillets',amount:'260 g'},{item:'Brown rice, cooked',amount:'1 cup'},{item:'Green beans',amount:'180 g'},{item:'Lemon',amount:'½'},{item:'Reduced-sodium soy sauce',amount:'1 tsp'}], instructions:['Grill mackerel skin-side down until crisp and cooked through.','Steam green beans until tender-crisp.','Divide rice and beans between bowls.','Add mackerel, lemon and a small drizzle of soy sauce.'], nutrition:{kcal:420,protein:30,carbs:40,fat:16,fiber:7,sodium:500}, tags:['High protein','Omega-rich','Meal prep'], accent:'blue' }),
  r({ id:'broccoli-prawn-stirfry', sourceId:'f433', name:'ผัดบรอกโคลีกุ้ง', englishName:'Broccoli Prawn Stir-fry', category:'Quick meals', cuisine:'Chinese', servings:2, prepMinutes:12, cookMinutes:10, ingredients:[{item:'Prawns, peeled',amount:'240 g'},{item:'Broccoli florets',amount:'280 g'},{item:'Garlic, sliced',amount:'3 cloves'},{item:'Oyster sauce',amount:'2 tsp'},{item:'Neutral oil',amount:'1 tsp'},{item:'Brown rice, cooked',amount:'1 cup'}], instructions:['Heat oil and cook garlic briefly until fragrant.','Add prawns and stir-fry until nearly cooked.','Add broccoli with 3 tbsp water, cover for 2 minutes.','Stir in oyster sauce and serve with rice.'], nutrition:{kcal:270,protein:20,carbs:30,fat:8,fiber:6,sodium:580}, tags:['High protein','Quick','Dairy-free'], accent:'lime' }),
  r({ id:'fruit-yogurt-bowl', sourceId:'f313', name:'โยเกิร์ตผลไม้และเมล็ดพืช', englishName:'Fruit Yogurt Seed Bowl', category:'Light bowls', cuisine:'American', servings:1, prepMinutes:8, cookMinutes:0, ingredients:[{item:'Plain Greek yogurt',amount:'170 g'},{item:'Mixed fruit',amount:'1 cup'},{item:'Chia seeds',amount:'1 tsp'},{item:'Oats',amount:'2 tbsp'},{item:'Cinnamon',amount:'a pinch'}], instructions:['Spoon yogurt into a bowl.','Top with fruit, oats and chia seeds.','Finish with cinnamon.','Serve straight away.'], nutrition:{kcal:290,protein:20,carbs:38,fat:7,fiber:7,sodium:95}, tags:['High protein','No-cook','Vegetarian'], accent:'coral' })
]

export function filterRecipes(items: Recipe[], filters: Filters): Recipe[] {
  const queryCategory = filters.category
  return items.filter(recipe =>
    (!queryCategory || recipe.category === queryCategory) &&
    (filters.maxKcal === undefined || recipe.nutrition.kcal <= filters.maxKcal) &&
    (filters.minProtein === undefined || recipe.nutrition.protein >= filters.minProtein) &&
    (filters.maxCarbs === undefined || recipe.nutrition.carbs <= filters.maxCarbs) &&
    (filters.maxFat === undefined || recipe.nutrition.fat <= filters.maxFat) &&
    (filters.maxSodium === undefined || (recipe.nutrition.sodium !== undefined && recipe.nutrition.sodium <= filters.maxSodium)) &&
    filters.tags.every(tag => recipe.tags.includes(tag))
  )
}

export function searchRecipes(items: Recipe[], rawQuery: string): Recipe[] {
  const query = rawQuery.trim().toLocaleLowerCase()
  if (!query) return items
  return items.filter(recipe => [recipe.name, recipe.englishName, recipe.category, recipe.cuisine, ...recipe.tags, ...recipe.ingredients.map(ingredient => ingredient.item)].join(' ').toLocaleLowerCase().includes(query))
}

export function chooseRandom(items: Recipe[], previousId?: string, random = Math.random): Recipe | undefined {
  if (!items.length) return undefined
  const choices = items.length > 1 && previousId ? items.filter(item => item.id !== previousId) : items
  return choices[Math.floor(random() * choices.length)]
}

export function validateRecipes(items: Recipe[]): string[] {
  const errors: string[] = []
  const ids = new Set<string>()
  const names = new Set<string>()
  const hasText = (value: unknown): value is string => typeof value === 'string' && value.trim().length > 0
  const hasNutrition = (value: unknown): value is Record<string, number> => typeof value === 'object' && value !== null && ['kcal', 'protein', 'carbs', 'fat'].every(key => typeof (value as Record<string, unknown>)[key] === 'number' && Number.isFinite((value as Record<string, number>)[key]) && (value as Record<string, number>)[key] >= 0) && Object.values(value).every(number => typeof number === 'number' && Number.isFinite(number) && number >= 0)
  for (const recipe of items) {
    const id = hasText(recipe.id) ? recipe.id : '(missing id)'
    const ingredients = Array.isArray(recipe.ingredients) ? recipe.ingredients : []
    const instructions = Array.isArray(recipe.instructions) ? recipe.instructions : []
    if (ids.has(id)) errors.push(`Duplicate id: ${id}`)
    if (hasText(recipe.name) && names.has(recipe.name)) errors.push(`Duplicate name: ${recipe.name}`)
    ids.add(id)
    if (hasText(recipe.name)) names.add(recipe.name)
    if (!hasText(recipe.id) || !hasText(recipe.name) || !hasText(recipe.englishName) || !hasText(recipe.cuisine) || !ingredients.length || !instructions.length || ingredients.some(ingredient => !hasText(ingredient?.item) || !hasText(ingredient?.amount)) || instructions.some(step => !hasText(step))) errors.push(`Missing required content: ${id}`)
    if (!Number.isInteger(recipe.servings) || recipe.servings <= 0 || !Number.isFinite(recipe.prepMinutes) || !Number.isFinite(recipe.cookMinutes) || recipe.prepMinutes < 0 || recipe.cookMinutes < 0) errors.push(`Invalid timing or servings: ${recipe.id}`)
    if (!hasNutrition(recipe.nutrition)) errors.push(`Invalid nutrition: ${id}`)
    else {
      const macroKcal = recipe.nutrition.protein * 4 + recipe.nutrition.carbs * 4 + recipe.nutrition.fat * 9
      if (Math.abs(recipe.nutrition.kcal - macroKcal) > 180) errors.push(`Nutrition sanity range: ${id}`)
    }
  }
  return errors
}
