import type { RecipeSeed } from './recipes'

export const recipeSlice5Seeds: RecipeSeed[] = [
  {"id":"tofu-waffle","sourceId":"slice5-01","name":"วาฟเฟิลเต้าหู้ซอสโยเกิร์ตมะนาว","englishName":"Tofu Waffles with Lime Yogurt Dip","category":"Quick meals","cuisine":"International","servings":2,"prepMinutes":15,"cookMinutes":15,"ingredients":[{"item":"Firm tofu, pressed and blended smooth","amount":"350 g"},{"item":"Eggs","amount":"2"},{"item":"Oats, finely ground","amount":"40 g"},{"item":"Spring onion, sliced","amount":"2 stalks"},{"item":"Reduced-sodium soy sauce","amount":"1 tbsp"},{"item":"Sesame oil","amount":"1 tsp"},{"item":"Greek yogurt","amount":"2 tbsp"},{"item":"Lime juice","amount":"1 tsp"},{"item":"Sesame seeds","amount":"1 tsp"}],"instructions":["Press tofu between paper towels or a clean cloth for 15 minutes to remove excess water, then blend it with the eggs until smooth.","Stir in the ground oats, half the spring onion and the soy sauce. Rest the batter for 5 minutes so the oats absorb moisture.","Brush a preheated waffle iron with sesame oil. Spoon in batter and cook until deeply golden and firm, about 5–6 minutes per waffle.","Stir the lime juice into the yogurt. Serve two waffles per person with the yogurt dip, the remaining spring onion and sesame seeds."],"nutrition":{"kcal":455,"protein":39,"carbs":20,"fat":24,"fiber":3,"sodium":365},"tags":["Vegetarian","Plant protein","Quick"],"accent":"violet"},
  {"id":"sweet-potato-kimchi","sourceId":"slice5-02","name":"มันหวานอบกิมจิ","englishName":"Roasted Sweet Potato with Kimchi","category":"Plant-forward","cuisine":"Korean","servings":2,"prepMinutes":10,"cookMinutes":25,"ingredients":[{"item":"Sweet potato, cut into 2 cm cubes","amount":"450 g"},{"item":"Kimchi, chopped","amount":"150 g"},{"item":"Neutral oil","amount":"1 tsp"},{"item":"Gochujang","amount":"1 tsp"},{"item":"Sesame oil","amount":"1 tsp"},{"item":"Spring onion, sliced","amount":"2 stalks"},{"item":"Sesame seeds","amount":"1 tsp"}],"instructions":["Toss the sweet potato cubes with the neutral oil on a lined tray. Roast at 200°C for 22–25 minutes, turning once, until tender and lightly caramelised at the edges.","Warm the kimchi in a small pan for 2–3 minutes until just softened, then stir in the gochujang.","Spoon the warm kimchi over the roasted sweet potato.","Drizzle with sesame oil and scatter with spring onion and sesame seeds before serving."],"nutrition":{"kcal":270,"protein":5,"carbs":49,"fat":6,"fiber":8,"sodium":690},"tags":["Vegetarian","Fiber-rich","Light"],"accent":"lime"},
  {"id":"konjac-kimchi-egg-noodles","sourceId":"slice5-03","name":"บุกผัดกิมจิไข่","englishName":"Konjac Noodles with Kimchi and Egg","category":"Light bowls","cuisine":"Korean","servings":2,"prepMinutes":10,"cookMinutes":10,"ingredients":[{"item":"Konjac noodles, drained and rinsed","amount":"400 g"},{"item":"Eggs","amount":"2"},{"item":"Kimchi, chopped","amount":"150 g"},{"item":"Gochujang","amount":"1 tsp"},{"item":"Reduced-sodium soy sauce","amount":"1 tsp"},{"item":"Bean sprouts","amount":"100 g"},{"item":"Sesame oil","amount":"1 tsp"},{"item":"Spring onion, sliced","amount":"2 stalks"},{"item":"Sesame seeds","amount":"1 tsp"}],"instructions":["Rinse and drain the konjac noodles well, then dry-fry them in a hot pan for 2 minutes to remove excess moisture.","Push the noodles aside, scramble the eggs in the same pan, then fold them through.","Add the kimchi, gochujang, soy sauce and bean sprouts; stir-fry for 3–4 minutes until the sprouts are just tender.","Drizzle with sesame oil, scatter with spring onion and sesame seeds, and serve immediately."],"nutrition":{"kcal":155,"protein":9,"carbs":11,"fat":8,"fiber":6,"sodium":725},"tags":["Light","Quick","Dairy-free"],"accent":"blue"},
  {"id":"wakame-egg-soup","sourceId":"slice5-04","name":"ซุปสาหร่ายวากาเมะไข่","englishName":"Wakame Egg Soup","category":"Light bowls","cuisine":"Japanese","servings":2,"prepMinutes":10,"cookMinutes":15,"ingredients":[{"item":"Dashi stock","amount":"700 ml"},{"item":"Wakame, dried","amount":"10 g"},{"item":"Firm tofu, cubed","amount":"150 g"},{"item":"Mushrooms, sliced","amount":"100 g"},{"item":"Eggs","amount":"2"},{"item":"Reduced-sodium soy sauce","amount":"1 tbsp"},{"item":"Sesame oil","amount":"1 tsp"},{"item":"Spring onion, sliced","amount":"2 stalks"}],"instructions":["Soak the dried wakame in cold water for 5 minutes until it softens and roughly triples in volume, then drain well.","Bring the dashi stock to a gentle simmer, stir in the soy sauce, then add the tofu and mushrooms and cook until the mushrooms soften.","Whisk the eggs, then pour them in a thin stream over the surface while gently stirring in one direction to form soft ribbons.","Stir in the rehydrated wakame, remove from the heat, and finish with sesame oil and spring onion."],"nutrition":{"kcal":240,"protein":22,"carbs":8,"fat":14,"fiber":1,"sodium":480},"tags":["Vegetarian","Light","Balanced"],"accent":"green"},
]

export const recipeImagePresentationSlice5: Record<string, string> = {
  'tofu-waffle': "Two golden crisp waffle-iron-pressed tofu waffles with a clearly visible waffle-grid texture, spring onion and sesame seeds on top, beside a small bowl of pale lime-yogurt dip. NO gochujang sauce, no rice.",
  'sweet-potato-kimchi': "Roasted orange sweet potato cubes with browned caramelized edges topped with warm red kimchi and a light sesame-oil sheen, spring onion and sesame seeds, in a simple bowl. NO rice, no separate protein.",
  'konjac-kimchi-egg-noodles': "A bowl of stir-fried translucent glassy konjac noodles with scrambled egg, red kimchi pieces, pale bean sprouts, spring onion and sesame seeds. Dry stir-fry, NO broth, no tofu.",
  'wakame-egg-soup': "Clear pale Japanese dashi broth in a bowl with dark green rehydrated wakame strands, soft egg ribbons, a few tofu cubes and sliced mushroom, spring onion on top. NO orange or creamy broth color, no whole boiled egg half.",
}
